echo "Hello from $USER running a script on `hostnam
e`" 
echo "" 
echo "SGE Variables:" 
echo "ARC = $ARC" 
echo "COMMD_PORT = $COMMD_PORT" 
echo "SGE_ROOT = $SGE_ROOT" 
echo "SGE_CELL = $SGE_CELL" 
echo "SGE_JOB_SPOOL_DIR = $SGE_JOB_SPOOL_DIR" 
echo "SGE_O_HOME = $SGE_O_HOME" 
echo "SGE_O_HOST = $SGE_O_HOST" 
echo "SGE_O_LOGNAME = $SGE_O_LOGNAME" 
echo "SGE_O_MAIL = $SGE_O_MAIL" 
echo "SGE_CKPT_ENV = $SGE_CKPT_ENV" 
echo "SGE_CKPT_DIR = $SGE_CKPT_DIR" 
echo "SGE_STDERR_PATH = $SGE_STDERR_PATH" 
echo "SGE_STDOUT_PATH = $SGE_STDOUT_PATH" 
echo "SGE_TASK_ID = $SGE_TASK_ID" 
echo "ENVIRONMENT = $ENVIRONMENT" 
echo "HOME = $HOME" 
echo "HOSTNAME = $HOSTNAME" 
echo "JOB_ID = $JOB_ID" 
echo "JOB_NAME = $JOB_NAME" 
echo "LOGNAME = $LOGNAME" 
echo "NHOSTS = $NHOSTS" 
echo "NQUEUES = $NQUEUES" 
echo "NSLOTS = $NSLOTS" 
sleep 20